### ISSUE TITLE
Missing utils.js

### ISSUE THREAD

**Issue by believer** [zth/reason-relay#17]
I'm seeing an issue that `utils.js` is missing. The require statement looks for `./utils` which doesn't exist in the compiled output in `/lib/js/src`. If I copy the `utils` file from `/src` everything starts working perfectly.

**Comment by zth** [comment]
Oops! Thanks, I'll fix it ASAP!

**Comment by believer** [comment]
Awesome, thanks! :smile:

**Comment by zth** [comment]
Fixed in `0.5.2`.

**Comment by believer** [comment]
@zth I'm still not seeing the `utils.js` in the compiled `lib/es6/src` with `0.5.2`? 🤔

**Comment by zth** [comment]
:thinking: @believer could you by any chance give me a way to reproduce?

**Comment by believer** [comment]
You should be able to see it in my [soundtrackdb](https://github.com/believer/soundtrackdb/packages/web)!

After installing (`yarn`):

- BuckleScript compiler (`yarn build`) - all good ✅ 
- Relay compiler (`yarn relay`) - all good ✅ 
- Webpack (webpack-dev-server) (`yarn server`) - Error ⛔️ 

```sh
ERROR in ./node_modules/reason-relay/lib/es6/src/ReasonRelay.bs.js
Module not found: Error: Can't resolve './utils' in '/Users/rickardlaurin/code/personal/soundtrackdb/packages/web/node_modules/reason-relay/lib/es6/src'
ℹ ｢wdm｣: Failed to compile.
```

Confirmed that I'm running `0.5.2` and have tried removing both `node_modules` and `yarn.lock` without any difference. Tell me if you need any more information 😄

**Comment by zth** [comment]
@believer thanks a lot, that's great!

**Comment by zth** [comment]
@believer quick question - is there a reason you've turned off `"in-source": true` in `bsconfig.json`? Could you try with that enabled and see if it works? In case you don't remember, it's configured in `package-specs`, right next to `"module": "es6"`.

**Comment by believer** [comment]
@zth yeah, I like to separate the built code from the Reason-files. I think the `src` feels cluttered when using `"in-source": true`. I usually don't need to look at the built files, so feels better to keep them "out of sight".

Regarding the issue, using `"in-source": true` seems to work fine since the code gets compiled to the `src` folder of `reason-relay`!

**Comment by zth** [comment]
Great, then we at least know what the problem is. I'll think about how I could support `in-source` too, and get back to you.

**Comment by believer** [comment]
Sweet! I'll keeping using `in-source` for now 😄

**Comment by zth** [comment]
I'm going to close this for now as there's a few other things that won't work without `in-source` right now. I can hopefully revisit this at a later point.
